version: '3.1'

services:
  database:
    container_name: nestjs_postgres
    image: postgis/postgis:11-3.0
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: nimda
      POSTGRES_USER: admin
      POSTGRES_DB: authentication
  database2:
    image: mongo
    container_name: nestjs_mongodb
    command: mongod --port 27018
    volumes:
    - ./mongo-volume:/data/db
    ports:
    - '27018:27018'
