export enum Permissions {
    ASSETS_CREATE = "ASSETS:CREATE",
    ASSETS_READ = "ASSETS:READ",
    ASSETS_UPDATE = "ASSETS:UPDATE",
    ASSETS_DELETE = "ASSETS:DELETE",
    ASSETS_SUGGEST = "ASSETS:SUGGEST"
}
