export enum PermissionsEnum {
    ASSETS_CREATE = "ASSETS_CREATE",
    ASSETS_READ = "ASSETS_READ",
    ASSETS_UPDATE = "ASSETS_UPDATE",
    ASSETS_DELETE = "ASSETS_DELETE",
    ASSETS_SUGGEST = "ASSETS_SUGGEST",
    ASSETS_CONNECT = "ASSETS_CONNECT",
    USER_CREATE = "USER_CREATE",
    USER_READ = "USER_READ",
    USER_UPDATE = "USER_UPDATE",
    USER_DELETE = "USER_DELETE",
    CONFIGURATION_CREATE = "CONFIGURATION_CREATE",
    CONFIGURATION_READ = "CONFIGURATION_READ",
    CONFIGURATION_UPDATE = "CONFIGURATION_UPDATE",
    CONFIGURATION_DELETE = "CONFIGURATION_DELETE"
}
